version: '3.8'

services:
  roundcube:
    image: roundcube/roundcubemail:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://imap-vip.uni5.net
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://smtp-vip.uni5.net
      - ROUNDCUBEMAIL_SMTP_PORT=587
mkdir -p ./roundcube-custom/skins/elastic/images
mkdir -p ./roundcube-custom/skins/elastic/templates
mkdir -p ./roundcube-custom/config
